# Request from browser => nginx => static or php, if not static => php-apache => static or php
# http://localhost:8000/nginx-index.html
# http://localhost:8000/apache-index.html
# http://localhost:8000/index.php
version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      HOSTNAME: db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 5
  apache:
    build: './php-apache'
    volumes:
      - ./public_html:/home/public_html
      - ./conf/8000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    # env_file: ./.env
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: './conf/nginx'
    volumes:
      - ./conf/nginx/conf/default.conf:/etc/nginx/nginx.conf
      - ./nginx-public_html:/home/public_html
    ports:
      - 8000:80
    depends_on:
      - apache
  redis:
    image: redis
    command: ["sh", "-c", "exec redis-server"]
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    container_name: mongoex
    ports:
      - 8081:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo
volumes:
  db_volume: