# Request from browser => nginx => static or php, if not static => php-apache => static or php
# http://localhost:8000/nginx-index.html
# http://localhost:8000/apache-index.html
# http://localhost:8000/index.php
version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      HOSTNAME: db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 10
  apache:
    build: './php-apache'
    volumes:
      - ./public_html:/home/public_html
      - ./conf/8000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    # env_file: ./.env
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: './conf/nginx'
    volumes:
      - ./conf/nginx/conf/default.conf:/etc/nginx/nginx.conf
      - ./nginx-public_html:/home/public_html
    ports:
      - 8000:80
    depends_on:
      - apache
  
volumes:
  db_volume: